version: "2"

services:
  notifier:
    build: .
    environment:
      DATABASE_URL: "mongodb://database/notifier"
      NEXMO_API_KEY: "<api key>"
      NEXMO_API_SECRET: "<api secret>"
      FIREBASE_KEY_PATH: "/opt/firebase-key.json"
    volumes:
      - "/opt/firebase-key.json:/opt/firebase-key.json"
    ports:
      - "8989:8989"
    networks:
      - notifier
    depends_on:
      - database
    command: yarn start    

  database:
    image: mongo:3.4.10
    networks:
      - notifier
    volumes:
      - data:/data/db
    command: mongod --enableMajorityReadConcern

networks:
  notifier:

volumes:
  data:
